version: 2
jobs:
  test_acc:
    docker: 
    - image: circleci/golang:1.13
    working_directory: ~/src/github.com/terraform-providers/terraform-provider-vsphere
    steps:
    - checkout
    - run:
        name: "Move to GOPATH"
        command: |
          mkdir -p $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
          mv /home/circleci/src/github.com/terraform-providers/terraform-provider-vsphere/* $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
    - add_ssh_keys:
        fingerprints:
          - "62:4d:8d:04:48:f7:0f:5a:63:da:de:a6:30:f4:b4:12"
    - run:
        name: "SSH Tunnel"
        command: |
          ssh root@147.75.90.29 -L 4430:vcenter.vsphere.hashicorptest.internal:443 -L 4431:esxi1.vsphere.hashicorptest.internal:443 -o StrictHostKeyChecking=no -f sleep 32400
    - run:
        name: "Get GOVC"
        command: |
          go get -u github.com/vmware/govmomi/govc
    - run:
        name: "Run Acceptance Tests"
        command: |
          $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere/scripts/test_runner.sh
  build:
    docker: 
    - image: circleci/golang:1.13
    working_directory: ~/src/github.com/terraform-providers/terraform-provider-vsphere
    steps:
    - checkout
    - run:
        name: "Move to GOPATH"
        command: |
          mkdir -p $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
          mv /home/circleci/src/github.com/terraform-providers/terraform-provider-vsphere/* $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
    - run:
        name: "Run Tests"
        command: |
          cd $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
          make test
    - run:
        name: "Run Build"
        command: |
          cd $GOPATH/src/github.com/terraform-providers/terraform-provider-vsphere
          make build
  linters:
    docker: 
    - image: circleci/golang:1.13
    working_directory: ~/src/github.com/terraform-providers/terraform-provider-vsphere
    steps:
    - checkout
    - run:
        name: "Get tfproviderlint"
        command: |
          go get github.com/bflad/tfproviderlint/cmd/tfproviderlint
    - run:
        name: "Run tfproviderlint"
        command: |
          tfproviderlint -AT00{1..3} -R00{2..4} -S0{{01..12},{14..19}}  ./...

workflows:
  version: 2
  commit:
    jobs:
      - build
      - linters
  nightly:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters: 
            branches:
              only:
                - master
    jobs:
      - build
      - linters
      - test_acc
